### ISSUE TITLE
Sprint

### ISSUE THREAD

**Issue by GeraldHamiltonWicks** [GeraldHamiltonWicks/login-system#1]
- [x] GeraldHamiltonWicks/login-system/issues/4
- [x] GeraldHamiltonWicks/login-system/issues/3
- [ ] GeraldHamiltonWicks/login-system/issues/2
- [ ] GeraldHamiltonWicks/login-system/issues/1
